/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emloyeetransfermanagement.frame;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class addProjectType extends javax.swing.JFrame {

    /**
     * Creates new form addProjectType
     */
    Connection conn = null;
    DBConnection connection = new DBConnection();
    PreparedStatement pst = null;
    ResultSet rs = null;
    public addProjectType() {
        conn = connection.dbConncetor();
        initComponents();
        RecuperProjectType();
    }

        public void autoID(){
        try {
            String query = "select TOP 1 ProjectTypeID from ProjectType order by ProjectTypeID desc";
            
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            
            if(rs.next()){
                int t1 = rs.getInt("ProjectTypeID");
                int id = t1 + 1;
                txtProjectTypeID.setText(String.valueOf(id));
            }
                    
            } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    
    public void hideButton(){
        ProjectTypeManagement mark = new ProjectTypeManagement();
        String marked = mark.mark();
        
        if(marked.equals("modify")){
            updateProjectType.setVisible(true);
        }else {
            updateProjectType.setVisible(false);
        }
        
        if(marked.equals("add")){
            saveProjectType.setVisible(true);
        }else{
            saveProjectType.setVisible(false);
        }
        
    }
    
    
public void RecuperProjectType(){
    ProjectTypeManagement modify = new ProjectTypeManagement();
    
    try {
        String test2 = modify.getTableResult();
        String query = "select * from ProjectType where ProjectTypeID = '"+test2+"'";
        
        pst = conn.prepareStatement(query);
        rs = pst.executeQuery();
        
        if(rs.next()){
            String t1 = rs.getString("ProjectTypeID");
            txtProjectTypeID.setText(t1);
            String t2 = rs.getString("ProjectTypeName");
            txtProjectTypeName.setText(t2);
            String t3 = rs.getString("Description");
            txtDescription.setText(t3);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error in sql");
        System.out.println(e);
    }
}

public void clear(){
    txtProjectTypeID.setText("");
    txtProjectTypeName.setText("");
    txtDescription.setText("");
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProjectTypeID = new javax.swing.JTextField();
        txtProjectTypeName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        saveProjectType = new javax.swing.JButton();
        updateProjectType = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextPane();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Project Type Information");

        jLabel2.setText("Project Type ID:");

        jLabel3.setText("Project Type Name:");

        txtProjectTypeID.setEditable(false);
        txtProjectTypeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectTypeIDActionPerformed(evt);
            }
        });

        jLabel4.setText("Description: ");

        saveProjectType.setText("Save");
        saveProjectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProjectTypeActionPerformed(evt);
            }
        });

        updateProjectType.setText("Update");
        updateProjectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProjectTypeActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txtDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(updateProjectType)
                            .addGap(18, 18, 18)
                            .addComponent(saveProjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProjectTypeName)
                                .addComponent(txtProjectTypeID)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProjectTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProjectTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateProjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveProjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void saveProjectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProjectTypeActionPerformed
        // TODO add your handling code here:
        try {
            String query = "insert into ProjectType(ProjectTypeID, ProjectTypeName, Description) values (?,?,?)";
            pst = conn.prepareStatement(query);
            
            pst.setString(1, txtProjectTypeID.getText());
            pst.setString(2, txtProjectTypeName.getText());
            pst.setString(3, txtDescription.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");
            
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error: Saving is fail");
        }finally{
            try {
            pst.close();
            dispose(); 
            } catch (SQLException e) {
                System.out.println(e);
            }            
        }
        
    }//GEN-LAST:event_saveProjectTypeActionPerformed

    private void updateProjectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProjectTypeActionPerformed
        try {
            String t1 = txtProjectTypeID.getText();
            String t2 = txtProjectTypeName.getText();
            String t3 = txtDescription.getText();
            
            
            String query = "update ProjectType set ProjectTypeName = '"+t2+"', Description = '"+t3+"' where ProjectTypeID = '"+t1+"'";
            pst = conn.prepareStatement(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error, Update fail");
        } finally{
            try {
                pst.close();
                dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        ProjectTypeManagement show = new ProjectTypeManagement();
        show.showRecord();
        
    }//GEN-LAST:event_updateProjectTypeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        hideButton();
    }//GEN-LAST:event_formWindowOpened

    private void txtProjectTypeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectTypeIDActionPerformed
        autoID();
    }//GEN-LAST:event_txtProjectTypeIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addProjectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addProjectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addProjectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addProjectType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addProjectType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton saveProjectType;
    private javax.swing.JTextPane txtDescription;
    private javax.swing.JTextField txtProjectTypeID;
    private javax.swing.JTextField txtProjectTypeName;
    private javax.swing.JButton updateProjectType;
    // End of variables declaration//GEN-END:variables
}
